# Generated by Django 5.2.4 on 2025-07-08 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="document",
        ),
        migrations.RemoveField(
            model_name="application",
            name="pushback_reason",
        ),
        migrations.RemoveField(
            model_name="application",
            name="status",
        ),
        migrations.AddField(
            model_name="application",
            name="overall_status",
            field=models.CharField(default="Pending", max_length=20),
        ),
        migrations.CreateModel(
            name="ApplicationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("incorporation", "Certificate of Incorporation"),
                            ("proof_of_address", "Proof of Address"),
                            ("license", "Business License"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file", models.FileField(upload_to="documents/%Y/%m/%d/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Pushback", "Pushback"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "pushback_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="applications.application",
                    ),
                ),
            ],
        ),
    ]
